name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
  
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make build/release

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@b36f842fa378d7cbf6695fcac86ecdcef3af8af3
        with:
          branch: gh-pages
          folder: build/release/final
          git-config-name: github-actions[bot]
          git-config-email: <>
          single-commit: true
